import smoothScroll from './modules/smoothScroll.js';
import scrollAnimation from './modules/scrollAnimation.js';
import tabNavigation from './modules/tabNavigation.js';
import navFaqList from './modules/navFaqList.js';
import scrollTop from './modules/scrollTop.js';
import modal from './modules/modal.js';
import tooltip from './modules/tooltip.js';
import dropdownMenu from './modules/dropdownMenu.js';
import menuMobile from './modules/menuMobile.js';
import animaNumbers from './modules/animaNumbers.js';

smoothScroll();
scrollAnimation();
tabNavigation();
navFaqList();
scrollTop();
modal();
tooltip();
dropdownMenu();
menuMobile();
animaNumbers();